project:
  type: default
  output-dir: _site
  render:
    - index.qmd
  resources:
    - index.pdf

lang: is
language:
  other-links-title: Önnur snið
bibliography: references.bib
csl: apa.csl
link-citations: true

format:
  html:
    default-image-extension: svg
    toc: true
    toc-title: Efnisyfirlit
    theme:
      light: cosmo
      dark: darkly
    appendix-cite-as: display
    other-links:
      - text: PDF (útgefin grein)
        icon: file-pdf
        href: index.pdf
