project:
  type: default
  output-dir: _site
  render:
    - index.qmd
  resources:
    - HI-Kennslurit_2025_Vidskiptagreind.pdf
    - img/

lang: is
language:
  other-links-title: Önnur snið
  appendix-attribution-cite-as: "Vinsamlega vitnið í þetta verk sem:"
bibliography: references.bib
csl: apa.csl
link-citations: true

format:
  haskoli-islands-html:
    lang: is
    default-image-extension: svg
    toc-title: Efnisyfirlit
    appendix-cite-as: display
    css: styles.css
    include-in-header:
      - text: |
          <link rel="icon" type="image/svg+xml" href="img/hi/favicon.svg">
    other-links:
      - text: PDF (útgefin grein)
        icon: file-pdf
        href: HI-Kennslurit_2025_Vidskiptagreind.pdf
